update wrangler version
cloudflare/managed-component-to-cloudflare-worker pull request #25
Opened 2024-09-30 23:31 UTC by babacarbasse

2024-10-07 18:31 UTC, mackenly requested changes
Hello! Could you bump this further to include 3.80? That's the minimum that supports the new persistent logging and that bump is required to use that. Adding these comments to avoid creating duplicate PRs that both bump wrangler.

I don't work for CF nor can I merge, but again adding these comments to prevent having duplicate PRs to bump wrangler.

2024-10-07 18:31 UTC, mackenly commented on package.json
> +  "name": "managed-component-to-cloudflare-worker-cli",
This probably shouldn't be changed.

2024-10-07 18:31 UTC, mackenly commented on package.json
> +    "wrangler": "^3.78.12"
If possible, can you bump to 3.80.1 or higher?

2025-02-11 09:43 UTC, omarmosid approved these changes

2025-02-11 16:44 UTC, omarmosid commented
closing in favour of: #27

2025-02-11 16:44 UTC, closed without merging